import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Header from "./Components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          
          <main className="container py-6 px-6 max-w-4xl mx-auto ">
            <Header /> 
            </main>
            <main className=" ">
              {children}
              <footer className="container p-6 m-2 font-bold text-gray-500 mx-auto">
              Job Board &copy; 2024 - All rights reserved
              </footer>
            </main>
             
             
            
           
            

         

       

        </body>
      </html>
    );
}
